"use strict";var f=Object.defineProperty;var w=Object.getOwnPropertyDescriptor;var $=Object.getOwnPropertyNames;var C=Object.prototype.hasOwnProperty;var E=(i,e)=>{for(var a in e)f(i,a,{get:e[a],enumerable:!0})},b=(i,e,a,m)=>{if(e&&typeof e=="object"||typeof e=="function")for(let r of $(e))!C.call(i,r)&&r!==a&&f(i,r,{get:()=>e[r],enumerable:!(m=w(e,r))||m.enumerable});return i};var k=i=>b(f({},"__esModule",{value:!0}),i);var j={};E(j,{default:()=>_});module.exports=k(j);var d=require("@libs/fetch"),g=require("@libs/defaultCover"),y=require("@libs/novelStatus"),I=require("@libs/pluginMetadata"),P=class{constructor(){this.id="yuneko.ophim";this.name="OPhim";this.icon="icon.png";this.site="https://ophim17.cc";this.version="1.0.3";this.apiUrl="https://ophim1.com/v1/api";this.contentType=I.ContentType.VIDEO;this.imageRequestInit={headers:{Referer:this.site+"/"}}}async popularNovels(e,a){let m=`${this.apiUrl}/danh-sach/phim-moi-cap-nhat?page=${e}`,o=await(await(0,d.fetchApi)(m)).json(),t=[],p=o.items||o.data&&o.data.items||[],h=o.pathImage||o.data&&o.data.params&&o.data.params.cdnDataRoot||"https://img.ophim.live/uploads/movies/";return p.forEach(c=>{let n=c.thumb_url;n&&!n.startsWith("http")&&(n=h+n),t.push({name:c.name,path:`/phim/${c.slug}`,cover:n||g.defaultCover})}),t}async searchNovels(e,a){let r=`https://ophim1.com/v1/api/tim-kiem?keyword=${encodeURIComponent(e.trim())}&page=${a}`,t=await(await(0,d.fetchApi)(r)).json(),p=[],h=t.data?.items||[],c="https://img.ophim.live/uploads/movies/";return h.forEach(n=>{let s=n.thumb_url;s&&!s.startsWith("http")&&(s=c+s),p.push({name:n.name,path:`/phim/${n.slug}`,cover:s||g.defaultCover})}),p}async parseNovel(e){let a=e.split("/").pop()?.replace(".html",""),m=`${this.apiUrl}/phim/${a}`,o=await(await(0,d.fetchApi)(m)).json();if(!o||!o.data||!o.data.item)throw new Error("Cannot fetch novel from OPhim API");let t=o.data.item,p=[];t.category&&t.category.forEach(l=>p.push(l.name)),t.country&&t.country.forEach(l=>p.push(l.name));let h=t.content?t.content.replace(/<[^>]*>/g,""):"",c=t.status!=="completed"?y.NovelStatus.Ongoing:y.NovelStatus.Completed,n=[];t.episodes&&t.episodes.forEach(l=>{let N=l.server_name;l.server_data.forEach(v=>{let u=v.name;u.toLowerCase().indexOf("tập")===-1&&(u="Tập "+u),n.push({name:u,path:v.link_m3u8||v.link_embed,page:N})})});let s=t.thumb_url;return s&&!s.startsWith("http")&&(s="https://img.ophim.live/uploads/movies/"+s),{path:e,name:t.name,cover:s||g.defaultCover,summary:h,author:t.director&&t.director.length>0&&t.director[0]!==""?t.director.join(", "):"Đang cập nhật",genres:p.join(", "),status:c,chapters:n}}async parseChapter(e){let a=e;return['<meta name="lnreader-chapter-type" content="video">','<meta name="lnreader-video-mode" content="direct">',`<meta name="lnreader-video-type" content="${!a.includes(".m3u8")?"iframe":"m3u8"}">`,`<meta name="lnreader-video-url" content="${a}">`,'<meta id="no-cache-marker"/>','<meta id="no-prefetch-marker"/>'].join(`
`)}resolveUrl(e,a){return e.startsWith("http")?e:this.site+e}},_=new P;
;if(module.exports.default)exports.default=(function resolvePluginAssets(plugin) {
  for (const field of ['icon', 'customCSS', 'customJS']) {
    const value = plugin[field];
    if (typeof value === 'string' && value && !value.includes('/')) {
      plugin[field] = `src/${plugin.id}/${value}`;
    }
  }
  return plugin;
})(module.exports.default);
