import { FilterTypes, Filters } from '@libs/filterInputs';

export default {
  sort: {
    type: FilterTypes.Picker,
    label: 'Sắp xếp theo',
    value: 'views_desc',
    options: [
      { label: 'Mới cập nhật', value: 'updated_desc' },
      { label: 'Lượt xem cao nhất', value: 'views_desc' },
      { label: 'Lượt xem thấp nhất', value: 'views_asc' },
      { label: 'Lượt lưu nhiều nhất', value: 'bookmarks_desc' },
      { label: 'Lượt lưu ít nhất', value: 'bookmarks_asc' },
      { label: 'Tên truyện A-Z', value: 'title_asc' },
      { label: 'Tên truyện Z-A', value: 'title_desc' },
      { label: 'Nhiều chương nhất', value: 'chapters_desc' },
      { label: 'Ít chương nhất', value: 'chapters_asc' },
      { label: 'Bình luận nhiều nhất', value: 'comments_desc' },
      { label: 'Bình luận ít nhất', value: 'comments_asc' },
    ],
  },
  status: {
    type: FilterTypes.Picker,
    label: 'Trạng thái',
    value: '',
    options: [
      { label: 'Tất cả trạng thái', value: '' },
      { label: 'Còn tiếp', value: 'ongoing' },
      { label: 'Hoàn thành', value: 'completed' },
      { label: 'Tạm dừng', value: 'hiatus' },
    ],
  },
  genre: {
    type: FilterTypes.CheckboxGroup,
    label: 'Thể loại',
    value: [],
    options: [
      { label: 'Action', value: '1' },
      { label: 'Adventure', value: '12' },
      { label: 'Comedy', value: '13' },
      { label: 'Doujinshi', value: '2716' },
      { label: 'Drama', value: '4' },
      { label: 'Ecchi', value: '64' },
      { label: 'Fantasy', value: '15' },
      { label: 'Gender Bender', value: '67' },
      { label: 'Harem', value: '65' },
      { label: 'Historical', value: '26' },
      { label: 'Horror', value: '16' },
      { label: 'Isekai', value: '46' },
      { label: 'Magic', value: '2720' },
      { label: 'Martial Arts', value: '192' },
      { label: 'Mystery', value: '2' },
      { label: 'Oneshot', value: '76' },
      { label: 'Psychological', value: '6' },
      { label: 'Romance', value: '19' },
      { label: 'School Life', value: '27' },
      { label: 'Sci-Fi', value: '7' },
      { label: 'Seinen', value: '3' },
      { label: 'Shounen', value: '8' },
      { label: 'Slice Of Life', value: '21' },
      { label: 'Supernatural', value: '22' },
      { label: 'Thriller', value: '2719' },
      { label: 'Time Travel', value: '49' },
      { label: 'Tragedy', value: '39' },
      { label: 'Truyện Việt', value: '2714' },
      { label: 'Yuri', value: '70' },
    ],
  },
} satisfies Filters;