import { FilterTypes, Filters } from '@libs/filterInputs';

export default {
  alphabet: {
    type: FilterTypes.Picker,
    value: '',
    label: 'Chữ cái',
    options: [
      { label: 'Tất cả', value: '' },
      { label: 'Khác', value: 'khac' },
      { label: 'A', value: 'a' },
      { label: 'B', value: 'b' },
      { label: 'C', value: 'c' },
      { label: 'D', value: 'd' },
      { label: 'E', value: 'e' },
      { label: 'F', value: 'f' },
      { label: 'G', value: 'g' },
      { label: 'H', value: 'h' },
      { label: 'I', value: 'i' },
      { label: 'J', value: 'j' },
      { label: 'K', value: 'k' },
      { label: 'L', value: 'l' },
      { label: 'M', value: 'm' },
      { label: 'N', value: 'n' },
      { label: 'O', value: 'o' },
      { label: 'P', value: 'p' },
      { label: 'Q', value: 'q' },
      { label: 'R', value: 'r' },
      { label: 'S', value: 's' },
      { label: 'T', value: 't' },
      { label: 'U', value: 'u' },
      { label: 'V', value: 'v' },
      { label: 'W', value: 'w' },
      { label: 'X', value: 'x' },
      { label: 'Y', value: 'y' },
      { label: 'Z', value: 'z' },
    ],
  },
  type: {
    type: FilterTypes.CheckboxGroup,
    label: 'Phân loại',
    value: ['truyendich', 'sangtac', 'convert'],
    options: [
      { label: 'Truyện dịch', value: 'truyendich' },
      { label: 'Truyện sáng tác', value: 'sangtac' },
      { label: 'Truyện AI dịch (Convert)', value: 'convert' },
    ],
  },
  status: {
    type: FilterTypes.CheckboxGroup,
    label: 'Tình trạng',
    value: ['dangtienhanh', 'tamngung', 'hoanthanh'],
    options: [
      { label: 'Đang tiến hành', value: 'dangtienhanh' },
      { label: 'Tạm ngưng', value: 'tamngung' },
      { label: 'Đã hoàn thành', value: 'hoanthanh' },
      { label: 'Truyện chưa duyệt', value: 'chuaduyet' },
    ],
  },
  sort: {
    type: FilterTypes.Picker,
    label: 'Sắp xếp',
    value: 'topthang',
    options: [
      { label: 'A-Z', value: 'tentruyen' },
      { label: 'Z-A', value: 'tentruyenza' },
      { label: 'Mới cập nhật', value: 'capnhat' },
      { label: 'Truyện mới', value: 'truyenmoi' },
      { label: 'Theo dõi', value: 'theodoi' },
      { label: 'Top toàn thời gian', value: 'top' },
      { label: 'Top tháng', value: 'topthang' },
      { label: 'Số từ', value: 'sotu' },
    ],
  },
} satisfies Filters;
